/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: akiprensky (https://sketchfab.com/akiprensky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/keyboard-9c3330dfbe4f4aecb0b4051fa5071598
Title: Keyboard
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from '@react-spring/three'

import keyboardScene from '../assets/3d/keyboard.glb'

const Keyboard = (props) => {
  const keyboardRef = useRef();
  const { nodes, materials } = useGLTF(keyboardScene);

  return (
    <a.group  red={keyboardRef} {...props}>
      <group scale={0.01}>
        <group
          position={[1855.72, 89.801, -320.466]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.Box152_Acrylic_Opaque_White_0.geometry}
            material={materials.Acrylic_Opaque_White}
            position={[0, -0.052, 0.029]}
          />
          <mesh
            geometry={nodes["Text007_Material_#34_0"].geometry}
            material={materials.Material_34}
            position={[-3.037, 4.263, 1.318]}
            rotation={[0.175, 0, 0]}
            scale={0.945}
          />
          <mesh
            geometry={nodes["Box192_Material_#34_0"].geometry}
            material={materials.Material_34}
            position={[-1.433, -4.762, 0.83]}
            scale={0.506}
          />
        </group>
      </group>
    </a.group>
  );
}

export default Keyboard;